Fix invalid inputs of bn256 could make vm exit.
nervosnetwork/godwoken pull request #1022
Opened 2023-03-13 07:38 UTC by magicalne

Handle errors in bn256 and return errors for syscalls.

2023-03-14 09:13 UTC, jjyr submitted a review, later dismissed

2023-03-14 09:13 UTC, jjyr commented on crates/generator/src/syscalls/bn.rs
>          G1::zero()
Is this a breaking change? (is `AffineG1(Fq::zero(), Fq::zero()) == G1::zero()`? )

2023-03-14 09:57 UTC, magicalne commented on crates/generator/src/syscalls/bn.rs
>          G1::zero()
Well, actually I don't break any change here. But after checking the code, looks like  `AffineG1(Fq::zero(), Fq::zero())` and `G1::zero()` are not equivalent.
`G1::zero()` represents:
```rust
        G {
            x: P::Base::zero(),
            y: P::Base::one(),
            z: P::Base::zero(),
        }
```

And for `AffineG1(Fq::zero(), Fq::zero())`:
```rust
      G {
           x: x,
           y: y,
           z: P::Base::one(),
     };
```

@Flouse Do you remember about this? Is that intended?

2023-03-17 08:00 UTC, Flouse requested changes

2023-03-17 08:00 UTC, Flouse commented on crates/generator/src/syscalls/mod.rs
> +                log::debug!("[bn256 input]: {:?}", &input[96..128]);
The `input_size` can be less than 128. This debug log may cause panic.

2023-03-17 14:34 UTC, Flouse commented on crates/generator/src/syscalls/bn.rs
>          G1::zero()
Yes, that is intended.

As my understanding, when `px == Fq::zero() && py == Fq::zero()`,
it is a special coordinate at infinity with `z == P::Base::zero()`. 

similar implementation: https://github.com/openethereum/parity-ethereum/blob/c7f608ec740882eac94038249037ddd955b60d31/ethcore/src/builtin.rs#L408-L414

2023-03-22 02:08 UTC, Flouse approved these changes, later dismissed

2023-03-22 04:42 UTC, Flouse approved these changes

2023-03-22 05:22 UTC, jjyr approved these changes

2023-03-22 05:23 UTC, merged