feat(statedb): support loading from checkpoint state
nervosnetwork/godwoken pull request #197
Opened 2021-05-25 07:02 UTC by zeroqn

Add ```CheckPoint```, ```SubState``` and ```StateDBMode```
Save every withdrawal and transaction post state to db
Able to load statedb from checkpoint(block_number with ```SubState```) and ```StateDBMode```

2021-05-26 05:05 UTC, jjyr requested changes
Please add a test case of state-DB with a withdrawal sub-state.

2021-05-26 05:05 UTC, jjyr commented on crates/block-producer/src/produce_block.rs
> +            StateDBMode::Write,
StateDBMode::ReadOnly,

2021-05-26 05:14 UTC, jjyr requested changes

2021-05-26 05:14 UTC, jjyr commented on crates/store/src/transaction.rs
> +        post_states: Vec<packed::AccountMerkleState>,
```suggestion
        withdrawal_receipts: Vec<packed::WithdrawalReceipt>,
```

2021-05-26 07:57 UTC, zeroqn commented
All Done

2021-05-26 12:11 UTC, jjyr requested changes

2021-05-26 12:11 UTC, jjyr commented on crates/store/src/state_db.rs
> +            .extract_block_number_and_index_number(&self.inner, self.mode)?;
We can use `.expect(...)` to eliminate the error here.

2021-05-26 12:11 UTC, jjyr commented on crates/store/src/state_db.rs
> +mod tests {
Put tests into crates/store/src/tests/state_db.rs

2021-05-26 12:11 UTC, jjyr commented on crates/store/src/transaction.rs
> +pub struct WithdrawalReceipt {
Put this into gw-types/store.mol

2021-05-27 03:22 UTC, jjyr approved these changes

2021-05-27 03:22 UTC, merged