feat(rpc-server): Support block parameter
nervosnetwork/godwoken pull request #238
Opened 2021-07-08 13:08 UTC by classicalliu

2021-07-10 08:46 UTC, jjyr requested changes

2021-07-10 10:57 UTC, classicalliu commented on crates/rpc-server/src/registry.rs
> +        None => return Ok(None),
infura `eth_call`

```json
{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32000,
        "message": "header not found"
    }
}
```

godwoken `execute_raw_l2transaction` now:

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": 0,
        "message": "header not found"
    },
    "id": 1
}
```

And another question is `get_balance` throws db error when `block_number` to big, should we unify this?

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": 0,
        "message": "DB error can't find block hash"
    },
    "id": 1
}
```

2021-07-12 02:08 UTC, jjyr commented on crates/rpc-server/src/registry.rs
> +        None => return Ok(None),
We should return a special code to represent block is not found, and the web3 server should check the returned code and return a ethereum-compatible response to users.

2021-07-12 02:12 UTC, jjyr commented on crates/rpc-server/src/registry.rs
> +        None => return Ok(None),
Return this error to specific a response code https://docs.rs/jsonrpc-v2/0.10.1/jsonrpc_v2/enum.Error.html

2021-07-12 06:27 UTC, classicalliu commented on crates/rpc-server/src/registry.rs
> +        None => return Ok(None),
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "header not found"
    },
    "id": 1
}
```

All RPCs which has block parameter param will check and throw this error when `block_number` bigger than tip.

2021-07-12 09:59 UTC, jjyr approved these changes

2021-07-12 10:00 UTC, merged