Fix mem pool restore mem block cause slow creation
nervosnetwork/godwoken pull request #485
Opened 2021-12-11 08:29 UTC by zeroqn

2021-12-12 00:52 UTC, jjyr commented on crates/rpc-server/src/registry.rs
> +            while let Some(hash) = mem_pool.reinject_txs_mut().last().cloned() {
```suggestion
            while let Some(hash) = mem_pool.reinject_txs_mut().pop() {
```

2021-12-12 00:52 UTC, jjyr commented on crates/mem-pool/src/pool.rs
> +    pub fn reinject_txs_mut(&mut self) -> &mut Vec<H256> {
```suggestion
    pub fn pending_restored_tx_hashes(&mut self) -> &mut Vec<H256> {
```

The name should be meaningful

2021-12-12 00:52 UTC, jjyr commented on crates/mem-pool/src/mem_block.rs
> +    pub fn emergency_reinject_restored_tx_hashes(&mut self, tx_hashes: &[H256]) {
```suggestion
    pub fn force_reinject_tx_hashes(&mut self, tx_hashes: &[H256]) {
```

2021-12-12 00:52 UTC, jjyr commented on crates/mem-pool/src/mem_block.rs
> +        self.txs.clear();
We should also clear `state_checkpoints` & `touched_keys`

2021-12-13 05:36 UTC, jjyr commented
pls add some tests and send pr to develop branch

2021-12-13 14:32 UTC, zeroqn commented
> pls add some tests and send pr to develop branch

Done

2021-12-20 13:55 UTC, jjyr requested changes

2021-12-20 13:55 UTC, jjyr commented on crates/mem-pool/src/restore_manager.rs
> +        let block = packed::CompactMemBlock::from_slice(&read(file_path)?)?;
Does this compatible this the current version?

2021-12-20 13:55 UTC, jjyr commented on crates/rpc-server/src/registry.rs
> +                match db.get_mem_pool_transaction(&hash) {
The order of txs is reverse? This may cause nonce error.

2021-12-20 15:12 UTC, zeroqn commented on crates/mem-pool/src/restore_manager.rs
> +        let block = packed::CompactMemBlock::from_slice(&read(file_path)?)?;
Fixed

2021-12-20 15:12 UTC, zeroqn commented on crates/rpc-server/src/registry.rs
> +                match db.get_mem_pool_transaction(&hash) {
Indeed. Fixed.

2021-12-21 04:36 UTC, jjyr approved these changes, later dismissed

2021-12-21 09:58 UTC, Flouse approved these changes, later dismissed

2021-12-21 09:58 UTC, Flouse commented on crates/types/src/offchain/extension.rs
> +    pub fn from_full_compitablie_slice(slice: &[u8]) -> Result<CompactMemBlock, VerificationError> {
rename it to from_full_compatible_slice ?

2021-12-21 10:15 UTC, zeroqn commented on crates/types/src/offchain/extension.rs
> +    pub fn from_full_compitablie_slice(slice: &[u8]) -> Result<CompactMemBlock, VerificationError> {
Fix typo

2021-12-22 03:18 UTC, jjyr approved these changes

2021-12-22 08:37 UTC, Flouse approved these changes

2021-12-22 09:31 UTC, merged