feat: Add ws server
nervosnetwork/godwoken pull request #510
Opened 2021-12-22 10:20 UTC by classicalliu

Add websocket server for notify error tx receipt

2021-12-24 02:22 UTC, jjyr requested changes

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/Cargo.toml
> +authors = ["jjy <jjyruby@gmail.com>"]
```suggestion
authors = ["Nervos network"]
```

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/notify_controller.rs
> +    fn handle_notify_new_error_tx_receipt(&mut self, msg: Result<ErrorTxReceipt, RecvError>) {
We should handle the Result type outside this function

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/notify_controller.rs
> +                    let _ = subscriber.send(error_tx_receipt.clone());
We should check the send error:

* if the channel is closed, we should remove the subscriber
* if the other error happend we should print a log

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/notify_controller.rs
> +            .spawn(move || loop {
We can use smol::spawn instead of start a new thread. The `Sender` and channel should be replaced with smol version

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/notify_controller.rs
> +            .spawn(move || loop {
Notice: we shouldn't depend on ckb_channel and ckb_stop_handler.

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/server.rs
> +    pub static ref GLOBAL_NOTIFY_CONTROLLER: Mutex<NotifyController> = Mutex::new(NotifyService::new().start(Some("NotifyService")));
Remove this global variable. we should pass controller to mem-pool struct.

2021-12-24 02:22 UTC, jjyr commented on crates/rpc-ws-server/src/subscription.rs
> +        thread_builder
Using smol

2022-01-11 02:44 UTC, jjyr submitted a review, later dismissed

2022-01-11 04:11 UTC, magicalne commented on crates/rpc-ws-server/Cargo.toml
> +jsonrpc-tcp-server = "18.0"
jsonrpc-http-server = "18.0"
jsonrpc-tcp-server = "18.0"
Looks like we don't need both crates ?

2022-01-11 06:47 UTC, magicalne approved these changes

2022-01-11 08:13 UTC, jjyr commented
@zeroqn Please check the test error in CI, it seems related to #505

2022-01-11 08:19 UTC, zeroqn commented
> @zeroqn Please check the test error in CI, it seems related to #505

Looks like random generated withdrawal count may be zero, i'll check again.

2022-01-11 09:50 UTC, jjyr approved these changes

2022-01-11 09:51 UTC, merged