feat(tools): support build with eth_addr_reg_validator
nervosnetwork/godwoken pull request #578
Opened 2022-02-10 09:25 UTC by magicalne

2022-02-10 10:36 UTC, Flouse requested changes
Please rebase `refs/pull/576/head`

2022-02-11 08:03 UTC, zeroqn approved these changes

2022-02-14 09:25 UTC, Flouse requested changes

2022-02-14 09:25 UTC, Flouse commented on crates/tools/src/prepare_scripts.rs
> +                    "eth_addr_reg_validator",
```suggestion
                    "eth_addr_reg_generator",
```

2022-02-14 15:05 UTC, Flouse approved these changes

2022-02-14 15:06 UTC, merged