Cherry pick tokio metrics v1 and tokio_kafka
nervosnetwork/godwoken pull request #622
Opened 2022-03-22 05:40 UTC by magicalne

- tokio-metrics
- tokio-console
- tokio_kafka
- tracing

2022-03-22 08:12 UTC, sopium reviewed
Other changes look fine but I did not look very closely.

2022-03-22 08:12 UTC, sopium commented on .github/workflows/rust.yml
> -        RUSTFLAGS: -D warnings
Doesn't removing this make the `clippy` check ineffective? The CI will pass even if there are clippy warnings.

2022-03-22 08:12 UTC, sopium commented on docs/debug_tokio.md
> +**tokio-console** also uses unstable rust features.
```suggestion
**tokio-console** also uses unstable tokio features.
```

2022-03-24 02:16 UTC, zeroqn approved these changes

2022-03-28 03:29 UTC, Flouse requested changes
@magicalne please rebase [nervosnetwork:compatibility-breaking-changes](https://github.com/nervosnetwork/godwoken/tree/compatibility-breaking-changes)

2022-03-30 01:35 UTC, merged