Update CHANGELOG.md
nervosnetwork/godwoken pull request #672
Opened 2022-04-25 05:05 UTC by ashleewang888

@Flouse

2022-04-25 06:55 UTC, sopium commented on CHANGELOG.md
> +### Compatiblility Improvements
```suggestion
### Ethereum Compatiblility Improvements
```

Otherwise it's not obvious with **what** the compatibility is improved.

2022-04-25 07:57 UTC, Flouse requested changes

2022-04-25 07:57 UTC, Flouse commented on CHANGELOG.md
> +- Fix total provisioning interface for sUDT ERC-20 proxy contract [#560](https://github.com/nervosnetwork/godwoken/pull/560)
```suggestion
- Fix `totalSupply` interface for sUDT ERC-20 proxy contract [#560](https://github.com/nervosnetwork/godwoken/pull/560)
```

2022-04-26 08:21 UTC, Flouse commented on CHANGELOG.md
> +- Change rollup cell's lock to omni-lock [#608](https://github.com/nervosnetwork/godwoken/pull/608). This PR enables the optimistic rollup to submit larger blocks to fix the inability of putting up t
```suggestion
- Change rollup cell's lock to omni-lock [#608](https://github.com/nervosnetwork/godwoken/pull/608). This PR enables the optimistic rollup to submit larger blocks to fix the inability of putting too much data in the witness field of a CKB transaction due to a secp256k1-lock limit.
```

2022-05-07 11:25 UTC, jjyr submitted a review, later dismissed

2022-05-07 11:33 UTC, Flouse approved these changes, later dismissed

2022-05-07 11:33 UTC, Flouse commented on CHANGELOG.md
> +v1 adds a new concept in having the Ethereum address registry stores Ethereum addresses in Godwoken. Once user deposits a new account, Godwoken will create a mapping between the Ethereum address and
```suggestion
v1 adds a new concept in having the Ethereum address registry stores Ethereum addresses in Godwoken. Once user deposits a new account, Godwoken will create a mapping between the Ethereum address and the account script hash. In addition, some RPCs have been adapted to support Ethereum addresses as parameters, and some Godwoken data structures have been adapted to support the new address format.
```

2022-05-07 11:34 UTC, merged