feat(rpc-server): recover polyjuice tx sender
nervosnetwork/godwoken pull request #710
Opened 2022-05-30 09:50 UTC by zeroqn

- feat: recover polyjuice tx sender from signature for ```submit_l2transaction``` and ```execute_l2transaction``` rpc
- feat: create sender account if not exists for ```submit_l2transaction``` rpc
- feat: support pass registry address for ```execute_raw_l2transaction``` rpc
- feat: add ```BatchCreateEthAccounts``` to ```MetaContractArgs``` (backward compatible) 

Recover rules:
- from id is 0
- nonce is 0
- valid signature
- correct registry address <-> script hash
- minimal ckb balance 21000

fix [godwoken-web3 issue #337](https://github.com/nervosnetwork/godwoken-web3/issues/337)

2022-05-30 09:50 UTC, zeroqn commented
/itest

2022-05-30 11:13 UTC, jjyr commented
Please rebase develop branch to pass the CI #709

2022-06-05 02:08 UTC, jjyr commented
> minimal ckb balance 21000

The original thought is to increase the cost of DOS by setting a higher limitation of transfer amount. But it won't help since the attacker can repeatedly transfer the coin to another account without additional cost.

2022-06-05 03:41 UTC, jjyr commented on crates/rpc-server/src/polyjuice_tx/eth_account_creator.rs
> +#![allow(clippy::mutable_key_type)]
This module should be moved in `gw-utils` or a new standalone crate.

2022-06-07 12:32 UTC, zeroqn commented on crates/rpc-server/src/polyjuice_tx/eth_account_creator.rs
> +#![allow(clippy::mutable_key_type)]
Refactor to `gw-polyjuice-sender-recover` crate

2022-06-09 04:46 UTC, Flouse commented
/itest

2022-06-09 11:49 UTC, zeroqn commented
/itest
kicker: master

2022-06-10 06:55 UTC, zeroqn commented
/itest

2022-07-06 05:45 UTC, Flouse commented
Please fix the conflicting files:
> crates/generator/src/account_lock_manage/secp256k1.rs
crates/rpc-server/src/registry.rs

2022-07-06 06:13 UTC, Flouse requested changes

2022-07-06 06:13 UTC, Flouse commented on docs/RPC.md
> +    * `registry_address`(optional): [`SerializedRegistryAddress`](#type-serializedregistryaddress) - Serialized registry address, **required for polyjuice tx from id zero**
```suggestion
    * `registry_address`(optional): [`SerializedRegistryAddress`](#type-serializedregistryaddress) - Serialized registry address, **required when the from_id of a Polyjuice transaction is 0.**
```

2022-07-06 06:13 UTC, Flouse commented on docs/RPC.md
> +For polyjuice tx from id zero, this RPC returns `null` because its from id will be updated
```suggestion
When the `from_id` of a Polyjuice transaction is 0, this RPC returns `null` because its `from_id` will be updated.
```

2022-07-06 07:40 UTC, Flouse commented on crates/polyjuice-sender-recover/src/recover/error.rs
> +    ChainId,
```suggestion
    InvalidChainId,
```

2022-07-07 10:36 UTC, Flouse commented on crates/polyjuice-sender-recover/src/recover/eth_recover.rs
> +    pub fn mock_sender_if_not_exists_from_raw_registery<S: State + CodeStore>(
Is `registery` a typo?

2022-07-07 10:37 UTC, magicalne commented on crates/polyjuice-sender-recover/src/recover/eth_account_creator.rs
> +    pub fn build_batch_create_tx<'a>(
Should this lifetime be removed?

2022-07-07 14:57 UTC, Flouse commented on docs/RPC.md
> +before package. To query in queue status of transation with `from_id` is 0, use transaction's signature hash.
```suggestion
When the `from_id` of a Polyjuice transaction is 0, this RPC returns `null` because the transaction
`from_id` will be updated before packing. To query the status of a pending transaction with `from_id = 0`,
please use the hash of the transaction signature as parameter.
```

2022-07-08 01:39 UTC, Flouse submitted a review, later dismissed

2022-07-11 03:08 UTC, sopium submitted a review, later dismissed

2022-07-12 09:45 UTC, jjyr approved these changes

2022-07-12 12:39 UTC, sopium approved these changes

2022-07-12 14:12 UTC, magicalne approved these changes

2022-07-12 15:53 UTC, Flouse approved these changes

2022-07-12 15:54 UTC, merged