fix: handle VM InvalidCycles by generate a polyjuice system log
nervosnetwork/godwoken pull request #729
Opened 2022-06-15 07:54 UTC by jjyr

* Handle `ckb_vm::error::Error::InvalidCycles` error raise form CKB VM
* Set `run_result.exit_code` to `1` in that case.
* Generate a polyjuice system log `account: raw_tx.to_id, gas_used: gas, cumulative_gas_used: gas, created_address: [0u8; 20], status: 0,`.

2022-06-15 10:04 UTC, classicalliu approved these changes, later dismissed

2022-06-15 12:38 UTC, zeroqn approved these changes, later dismissed

2022-06-16 03:43 UTC, Flouse requested changes

2022-06-16 03:43 UTC, Flouse commented on crates/generator/src/generator.rs
> +                Ok(_exit_code) => {
If Polyjuice return before [`emit_evm_result_log` function](https://github.com/nervosnetwork/godwoken-polyjuice/blob/1.2-rc/c/polyjuice.h#L1384),
Polyjuice may return an `exit_code` without `POLYJUICE_SYSTEM_LOG`.

2022-06-16 04:33 UTC, Flouse approved these changes, later dismissed

2022-06-16 05:01 UTC, Flouse commented on crates/generator/src/generator.rs
> +                Ok(_exit_code) => {
https://github.com/nervosnetwork/godwoken/pull/729/commits/4d7112652da9c5a5a065f37b486b67a0caeae765

2022-06-16 05:04 UTC, Flouse approved these changes

2022-06-16 05:59 UTC, magicalne approved these changes

2022-06-21 04:12 UTC, merged