fix: Update parse log
nervosnetwork/godwoken pull request #752
Opened 2022-07-05 03:24 UTC by classicalliu

2022-07-06 04:48 UTC, sopium commented on crates/utils/src/script_log.rs
> +    let to_address = match RegistryAddress::from_slice(&data[start..end]) {
Use `get(start..end)` to avoid panic?

2022-07-08 04:43 UTC, jjyr requested changes

2022-07-08 04:43 UTC, jjyr commented on crates/utils/src/script_log.rs
> +    let mut start = 0;
check length of data to avoid panic.

2022-07-11 03:17 UTC, classicalliu commented on crates/utils/src/script_log.rs
> +    let to_address = match RegistryAddress::from_slice(&data[start..end]) {
Updated

2022-07-11 03:17 UTC, classicalliu commented on crates/utils/src/script_log.rs
> +    let mut start = 0;
Updated

2022-07-12 09:18 UTC, jjyr approved these changes

2022-07-12 12:40 UTC, sopium approved these changes

2022-07-13 02:24 UTC, merged