Validate native token transfer raw tx and signature.
nervosnetwork/godwoken pull request #788
Opened 2022-08-24 06:38 UTC by magicalne

- check to_id == polyjuice_creator_id
- update `verify_tx` for native token transfer

2022-08-25 02:39 UTC, keroro520 approved these changes, later dismissed

2022-08-25 02:39 UTC, keroro520 commented on crates/utils/src/polyjuice_parser.rs
> +        self.is_call() && self.to_address().is_some()
What about using `!self.is_create()`?
 
```
        !self.is_create() && self.to_address().is_some()
```

2022-08-25 02:47 UTC, magicalne commented on crates/utils/src/polyjuice_parser.rs
> +        self.is_call() && self.to_address().is_some()
Always accepts call: https://github.com/nervosnetwork/godwoken-polyjuice/pull/173#discussion_r946744062

2022-08-26 04:04 UTC, zeroqn approved these changes, later dismissed

2022-08-29 02:45 UTC, jjyr requested changes

2022-08-29 02:45 UTC, jjyr commented on crates/generator/src/generator.rs
> +    pub fn get_polyjuice_creator_id<S: State + CodeStore>(
This function can be defined in `utils` module since it is not related to generator's logic, we can pass the backend manage as the parameter.

2022-08-29 02:45 UTC, jjyr commented on crates/generator/src/verification/transaction.rs
> +    pub fn new(state: &'a S, generator: Arc<Generator>) -> Self {
We can read `polyjuice_creator_id` from parameter to avoid duplicated DB read.

2022-08-29 02:45 UTC, jjyr commented on crates/generator/src/verification/transaction.rs
> +            if let Some(parser) = tx.parser() {
return an error if failed to parse

2022-08-30 03:04 UTC, jjyr approved these changes, later dismissed

2022-08-30 03:05 UTC, jjyr commented
/itest

2022-08-31 03:05 UTC, zeroqn commented on crates/generator/src/verification/transaction.rs
> +                if Some(to_id) != self.polyjuice_creator_id && self.polyjuice_creator_id.is_some() {
if ```polyjuice_creator_id``` is ```None```, this check will pass? Caller must ensure ```polyjuice_creator_id``` is ```Some```?
Maybe pass ```beckend_manage``` and call ```utils::get_polyjuice_creator_id``` if ```polyjuice_creator_id``` is ```None```?

2022-08-31 04:59 UTC, jjyr requested changes

2022-08-31 04:59 UTC, jjyr commented on crates/mem-pool/src/pool.rs
> +        let state = snap.state()?;
Move these to line to the if branch, we only need the `state` when `if self.polyjuice_creator_id.is_none()` returns true.

2022-08-31 11:05 UTC, jjyr approved these changes

2022-09-01 03:12 UTC, keroro520 approved these changes

2022-09-01 03:39 UTC, merged