doc: legacy withdrawal cell
nervosnetwork/godwoken pull request #803
Opened 2022-09-23 06:44 UTC by jjyr

2022-09-23 06:55 UTC, Flouse submitted a review, later dismissed

2022-09-23 07:26 UTC, Flouse commented on docs/deposit_and_withdrawal.md
> +* owner lock - If users submit withdrawal request with a owner lock structure. The block producer will generate withdrawal cells with `owner lock` field in the args, and automatically unlock these ce
```suggestion
* owner lock - If users submit withdrawal request with an owner lock structure. The block producer will generate withdrawal cells with `owner lock` field in the args, and automatically unlock these cells after they are finalized. Users don't need to manually unlock layer-1 withdrawal cells.
```

2022-09-23 07:26 UTC, Flouse commented on docs/deposit_and_withdrawal.md
> +We have optional fields in the withdrawal cell's args:
```suggestion
We have **optional** fields in the withdrawal cell's args:
```

2022-09-23 07:26 UTC, Flouse commented on docs/deposit_and_withdrawal.md
> +* withdrawal_to_v1 - This field only works when `owner lock` exist, if `withdrawal_to_v1` is exist and the value is `1`, which means the withdrawal is a fast withdraw to v1 Godwoken, the withdraw can
```suggestion
* withdrawal_to_v1 - This field only works when `owner lock` exist, if `withdrawal_to_v1` is exist and the value is `1`, which means the withdrawal is a fast withdrawal to Godwoken v1. A fast withdrawal from v0 to v1 can be instantly processed, and the assets will be migrated to Godwoken v1.
```

2022-09-23 07:26 UTC, Flouse commented on docs/deposit_and_withdrawal.md
> +* manually withdrawl - If `owner lock` do not exist, users must manually unlock the legacy withdrawal cell after it finalized, and user must provides an input cell in the unlocking transaction that i
```suggestion

### **Note**:
manually withdrawl - If `owner lock` do not exist, users must manually unlock the legacy withdrawal cell after it is finalized, and user must provides an input cell in the unlocking transaction that its `lock hash` is equals to withdrawal lock args' `owner_lock_hash`.
```

2022-09-25 15:40 UTC, ShookLyngs requested changes

2022-09-25 15:40 UTC, ShookLyngs commented on docs/deposit_and_withdrawal.md
> +manually withdrawl - If `owner lock` do not exist, users must manually unlock the legacy withdrawal cell after it is finalized, and user must provides an input cell in the unlocking transaction that
do not exist -> does not exist

2022-09-26 04:00 UTC, Flouse approved these changes

2022-09-26 07:58 UTC, merged