fix(mem-pool): remove re-injected failed txs in mem pool
nervosnetwork/godwoken pull request #831
Opened 2022-10-27 05:51 UTC by zeroqn

2022-10-27 10:09 UTC, Flouse requested changes
Please rebase on latest develop branch.

2022-10-28 08:58 UTC, jjyr approved these changes, later dismissed

2022-10-31 07:25 UTC, zeroqn commented
> > Run Result
> > failure
> 
> => Please rebase on latest develop branch.

Done

2022-10-31 08:01 UTC, Flouse approved these changes

2022-10-31 08:40 UTC, sopium approved these changes

2022-11-01 15:27 UTC, merged