chore: update polyjuice dep refs
nervosnetwork/godwoken pull request #851
Opened 2022-11-11 05:14 UTC by magicalne

Make polyjuice reference deps in the monorepo.

2022-11-11 07:06 UTC, Flouse requested changes

2022-11-11 07:06 UTC, Flouse commented on gwos-evm/README.md
> +git submodule update --init  --recursive
```suggestion
git submodule update --init --recursive --depth=1
```

2022-11-11 07:06 UTC, Flouse commented on gwos-evm/Makefile
> +GW_SCRIPTS := deps/gwos/c
```bash
@Flouse ➜ /workspaces/godwoken/gwos-evm (poly_ref ✗) $ make dist

# error
cat: deps/gwos/c/Makefile: No such file or directory
cat: deps/gwos/c/Makefile: No such file or directory
```

2022-11-22 08:12 UTC, keroro520 approved these changes, later dismissed

2022-11-22 12:32 UTC, magicalne commented
CI was fixed.

2022-11-23 01:09 UTC, keroro520 approved these changes, later dismissed

2022-11-23 01:09 UTC, keroro520 commented on .github/workflows/gwos-evm-ci.yml
> +        GODWOKEN_TESTS_REF=develop
it is reduandent

2022-11-23 08:20 UTC, keroro520 approved these changes

2022-11-23 08:28 UTC, zeroqn approved these changes

2022-11-26 13:23 UTC, Flouse approved these changes

2022-11-26 13:24 UTC, merged