chore: bump monorepo version to 0.12.0-rc1
nervosnetwork/godwoken pull request #975
Opened 2023-02-08 09:55 UTC by jjyr

[CHANGELOG]https://github.com/jjyr/godwoken/blob/deaa095c57edc0a599453ca003f4b0684a4f4971/CHANGELOG.md

2023-02-09 08:05 UTC, Flouse requested changes

2023-02-09 08:05 UTC, Flouse commented on CHANGELOG.md
> +We introduce a breaking change of the config file in [#946](https://github.com/godwokenrises/godwoken/pull/946). The consensus-related options are moved into option `consensus`, and we put the `testn
```suggestion
We introduced a breaking change of the config file in [#946](https://github.com/godwokenrises/godwoken/pull/946). The consensus-related options are moved into option `consensus`, and we put the builtin `testnet` and `mainnet` consensus into the godwoken program. This change reduces the operation works of node maintainers.
```

2023-02-09 12:29 UTC, Flouse approved these changes

2023-02-09 12:39 UTC, Simon-Tl approved these changes

2023-02-13 06:26 UTC, RetricSu commented on web3/package.json
> +  "version": "1.12.0-rc1",
we should remove the special tag handling in web3 CI:
- web3-docker-publish.yml
- web3-indexer-docker-publish.yml

eg:

- https://github.com/godwokenrises/godwoken/blob/develop/.github/workflows/web3-docker-publish.yml#L69-L74
- https://github.com/godwokenrises/godwoken/blob/develop/.github/workflows/web3-indexer-docker-publish.yml#L9

2023-02-13 10:14 UTC, RetricSu approved these changes

2023-02-13 10:14 UTC, RetricSu commented on web3/Dockerfile
> +WORKDIR /godwoken-web3
```suggestion
```

2023-02-13 10:14 UTC, RetricSu commented on web3/Dockerfile
>  RUN yarn && yarn build
```suggestion
RUN cd /godwoken-web3 && yarn && yarn build
```
see https://github.com/godwokenrises/godwoken/commit/1a3174548febd199a44ccd331ba4d64299676014#diff-6ec036556353d556083fa7858cef52cfece85508440e56c79c9c9d3476b96a35L5

2023-02-13 11:57 UTC, merged